# Generated by Django 2.1.2 on 2018-11-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='category',
        ),
    ]
