# Generated by Django 2.1.2 on 2018-11-04 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('object1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a', to='matches.Object')),
                ('object2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='matches.Object')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('object1', 'object2')},
        ),
    ]
