# Generated by Django 2.1.2 on 2018-11-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='ans_irrelevant',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
