# Generated by Django 2.1.2 on 2018-11-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_rate_ans_irrelevant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressrate',
            name='rates',
        ),
        migrations.AddField(
            model_name='rate',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AddressRate',
        ),
    ]
