# Generated by Django 2.1.2 on 2018-11-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20181104_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='rate',
        ),
        migrations.AddField(
            model_name='rate',
            name='ans_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='ans_yes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
