# Generated by Django 2.1.2 on 2018-11-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20181104_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='object',
            old_name='object',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='rate',
            name='ans_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='ans_yes',
            field=models.IntegerField(default=0),
        ),
    ]
