# Generated by Django 2.1.2 on 2018-11-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20181105_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='ans_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matches',
            name='ans_yes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rate',
            name='ans_no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='ans_yes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
