# Generated by Django 2.1.2 on 2018-11-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20181106_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='ans_no',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='ans_yes',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='ans_no',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='ans_yes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
