# Generated by Django 2.1.2 on 2018-11-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_auto_20181112_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='modified',
            field=models.DateTimeField(blank=True),
        ),
    ]
