# Generated by Django 2.1.2 on 2018-11-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_addressrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressrate',
            name='rate',
        ),
        migrations.AddField(
            model_name='addressrate',
            name='rate',
            field=models.ManyToManyField(to='matches.Rate'),
        ),
    ]
