# Generated by Django 2.1.2 on 2018-11-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_auto_20181112_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(blank=True)),
                ('ans_yes', models.PositiveIntegerField(default=0, null=True)),
                ('ans_no', models.PositiveIntegerField(default=0, null=True)),
                ('ans_irrelevant', models.PositiveIntegerField(default=0, null=True)),
                ('rates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Rate', unique=True)),
            ],
        ),
    ]
