# Generated by Django 2.1.2 on 2018-11-06 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_auto_20181107_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressrate',
            old_name='rate',
            new_name='rates',
        ),
    ]
