# Generated by Django 2.1.2 on 2018-11-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_auto_20181113_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateanswer',
            name='rates',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matches.Rate'),
        ),
    ]
