# Generated by Django 2.1.2 on 2018-11-13 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_auto_20181113_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateanswer',
            name='rates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.Rate'),
        ),
        migrations.AlterUniqueTogether(
            name='dateanswer',
            unique_together={('date', 'rates')},
        ),
    ]
