# Generated by Django 2.1.2 on 2018-11-13 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_auto_20181113_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateanswer',
            old_name='rates',
            new_name='rate',
        ),
        migrations.AlterUniqueTogether(
            name='dateanswer',
            unique_together={('date', 'rate')},
        ),
    ]
