# Generated by Django 2.1.2 on 2018-11-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0012_auto_20181113_1616'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dateanswer',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='dateanswer',
            name='rate',
        ),
        migrations.AddField(
            model_name='object',
            name='plural',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='DateAnswer',
        ),
    ]
